### PR TITLE
Go to v2.0.0 🚀

### LINKED ISSUE #5: Switch to html-minifier-terser

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
Fix #5 ✔️

### CODE REVIEW

**Comment by 3imed-jaberi** [comment]
@jonathanong, 
Kindly, can you check this PR and then merge it?

**Comment by jonathanong** [comment]
@3imed-jaberi adding you as collaborator

**Comment by 3imed-jaberi** [comment]
@jonathanong, give me the npm access

`npm owner add 3imed-jaberi koa-html-minifier`

**Comment by jonathanong** [comment]
done!

**Pull request merged**
