### PR TITLE
feat: update to koa 2

### PR DESCRIPTION
**Pull request by jpsc**
Update to koa2 and async await

### CODE REVIEW

**Comment by jonathanong** [comment]
@jpsc sorry, not maintaining this. would you like to maintain this?

**Comment by jpsc** [comment]
@jonathanong sure.

**Comment by CKarper** [comment]
Can we get this merged?

**Comment by jpsc** [comment]
I can merge it but I can't publish it. You can point to github.

**Comment by romain-faust** [comment]
@jonathanong can you publish the update ?

**Pull request merged**
